aliases:
  - &install-dependencies
    name: Install dependencies
    command: |
      apk add --update --no-cache nodejs nodejs-npm python3 make g++ pkgconfig libsecret-dev
      npm config set unsafe-perm true
      npm i -g npm
      node --version
      npm --version
      npm install
      npm run build-ui

version: 2
jobs:
  release_latest:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t nrvdwrf/ligna-server:latest .
            docker push nrvdwrf/ligna-server:latest
  release_branch:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t nrvdwrf/ligna-server:${CIRCLE_BRANCH} .
            docker push nrvdwrf/ligna-server:${CIRCLE_BRANCH}
  release_tag:
    working_directory: /app
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: *install-dependencies
      - run:
          name: Release Production Image
          command: |
            set +o pipefail
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
            docker build --no-cache -t nrvdwrf/ligna-server:${CIRCLE_TAG} .
            docker push nrvdwrf/ligna-server:${CIRCLE_TAG}

workflows:
  version: 2
  build_pipeline:
    jobs:
      - release_latest:
          filters:
            branches:
              only: master
      - release_branch:
          filters:
            branches:
              ignore: master
      - release_tag:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.+$/
